server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pizzadb}
    username: ${DB_USER:pizza}
    password: ${DB_PASSWORD:pizza}

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: INFO
